from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('register/',                     views.register_view,        name='register'),
    path('login/',                        views.login_view,           name='login'),
    path('logout/',                       views.logout_view,          name='logout'),
    path('dashboard/',                    views.dashboard_view,       name='dashboard'),
    path('verify-email/<uid>/<token>/',   views.verify_email_view,    name='verify_email'),
    path('forgot-password/',              views.forgot_password_view, name='forgot_password'),
    path('reset-password/<uid>/<token>/', views.reset_password_view,  name='reset_password'),
    path('profile/create/step/<int:step>/', views.profile_create_view, name='profile_create_step'),
    path('profile/', views.profile_detail_view, name='profile_detail'),
    path('verify-profile/', views.verify_profile_view, name='verify_profile'),
    path('partner-preferences/', views.partner_preference_view, name='partner_preferences'),
    path('browse/',                         views.browse_profiles_view, name='browse_profiles'),
    path('send-interest/<int:user_id>/',    views.send_interest_view,   name='send_interest'),
    path('respond-interest/<int:interest_id>/', views.respond_interest_view, name='respond_interest'),
    path('my-interests/',                   views.my_interests_view,    name='my_interests'),
    path('conversations/',                  views.my_conversations_view, name='conversations'),
    path('chat/<int:user_id>/',             views.chat_view,             name='chat'),
    path('invite-wali/<int:conversation_id>/', views.invite_wali_view,  name='invite_wali'),
    path('wali-access/<uuid:token>/',       views.wali_access_view,      name='wali_access'),
    path('notifications/',                      views.notifications_view,           name='notifications'),
    path('mark-read/<int:notif_id>/',           views.mark_notification_read_view,  name='mark_notification_read'),
    path('pricing/',         views.pricing_view,        name='pricing'),
    path('upgrade/',         views.upgrade_view,         name='upgrade'),
    path('my-subscription/', views.my_subscription_view, name='my_subscription'),
    path('admin-panel/login/',                              views.admin_login_view,                  name='admin_login'),
    path('admin-panel/logout/',                             views.admin_logout_view,                 name='admin_logout'),
    path('admin-panel/',                                    views.admin_dashboard_view,              name='admin_dashboard'),
    path('admin-panel/users/',                              views.admin_users_view,                  name='admin_users'),
    path('admin-panel/users/<int:user_id>/',                views.admin_user_detail_view,            name='admin_user_detail'),
    path('admin-panel/users/<int:user_id>/block/',          views.admin_block_user_view,             name='admin_block_user'),
    path('admin-panel/users/<int:user_id>/delete/',         views.admin_delete_user_view,            name='admin_delete_user'),
    path('admin-panel/subscriptions/',                      views.admin_subscriptions_view,          name='admin_subscriptions'),
    path('admin-panel/subscriptions/<int:sub_id>/approve/', views.admin_approve_subscription_view,   name='admin_approve_subscription'),
    path('admin-panel/subscriptions/<int:sub_id>/reject/',  views.admin_reject_subscription_view,    name='admin_reject_subscription'),
]