# Generated by Django 6.0.3 on 2026-03-10 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('caste_sect', models.CharField(blank=True, max_length=60)),
                ('marital_status', models.CharField(blank=True, choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('has_children', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('purpose', models.CharField(blank=True, choices=[('marriage', 'Marriage'), ('serious_relation', 'Serious Relationship'), ('family_request', 'Family Request')], max_length=20)),
                ('heard_from', models.CharField(blank=True, choices=[('social_media', 'Social Media'), ('app_store', 'App Store'), ('friends', 'Friends'), ('ads', 'Ads')], max_length=20)),
                ('education', models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('faith_level', models.CharField(blank=True, choices=[('very', 'Very Practicing'), ('moderate', 'Moderate'), ('somewhat', 'Somewhat Practicing')], max_length=10)),
                ('born_muslim', models.CharField(blank=True, choices=[('yes', 'Yes'), ('revert', 'Revert')], max_length=10)),
                ('halal_food', models.CharField(blank=True, choices=[('always', 'Always'), ('sometimes', 'Sometimes'), ('not_strict', 'Not Strict')], max_length=15)),
                ('dress_style', models.CharField(blank=True, choices=[('modest', 'Modest'), ('somewhat_modest', 'Somewhat Modest'), ('modern', 'Modern')], max_length=20)),
                ('smoking', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('drinking', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('grew_up_in', models.CharField(blank=True, max_length=100)),
                ('open_to_abroad', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('about_me', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
