# Generated by Django 6.0.3 on 2026-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_badge',
            field=models.BooleanField(default=False),
        ),
    ]
