# Generated by Django 6.0.3 on 2026-03-12 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_phone_verified_profile_selfie_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveIntegerField(default=18)),
                ('max_age', models.PositiveIntegerField(default=40)),
                ('preferred_country', models.CharField(blank=True, max_length=60)),
                ('preferred_caste_sect', models.CharField(blank=True, max_length=60)),
                ('preferred_ethnicity', models.CharField(blank=True, max_length=60)),
                ('preferred_marital_status', models.CharField(choices=[('any', 'Any'), ('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='any', max_length=20)),
                ('preferred_education', models.CharField(choices=[('any', 'Any'), ('high_school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='any', max_length=20)),
                ('preferred_faith_level', models.CharField(choices=[('any', 'Any'), ('very', 'Very Practicing'), ('moderate', 'Moderate'), ('somewhat', 'Somewhat Practicing')], default='any', max_length=10)),
                ('preferred_smoking', models.CharField(choices=[('any', 'Any'), ('no', 'Non Smoker'), ('yes', 'Smoker')], default='any', max_length=5)),
                ('preferred_drinking', models.CharField(choices=[('any', 'Any'), ('no', 'Non Drinker'), ('yes', 'Drinker')], default='any', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
